// auth types in reducers

export const GET_DAILY_WEATHER = 'WEATHER/GET_DAILY';
export const GET_DAILY_WEATHER_SUCCESS = 'WEATHER/GET_DAILY_SUCCESS';
export const GET_DAILY_WEATHER_FAIL = 'WEATHER/GET_DAILY_FAIL';

export const GET_FUTURE_WEATHER_SUCCESS = 'WEATHER/GET_FUTURE_WEATHER_SUCCESS';
export const GET_FUTURE_WEATHER_FAIL = 'WEATHER/GET_FUTURE_WEATHER_FAIL';
