import {StyleSheet} from 'react-native';
import {
  PRIMARY_BLUE,
  PRIMARY_DARK,
  PRIMARY_GRAY_BACKGROUND,
  PRIMARY_GRAY_BORDER,
  PRIMARY_LIGHT,
  PRIMARY_LIGHT_BLUE,
  TABBAR_DISABLE_UNDERLINE,
} from 'constants/colors';
import {
  size_214,
  txtSize_24,
  size_110,
  size_129,
  size_405,
  size_500,
  borderRadius_10,
  size_90,
  size_10,
  txtSize_22,
  size_15,
  size_32,
  size_72,
  txtSize_48,
  size_59,
  txtSize_36,
  size_43,
  size_353,
  size_52,
  size_60,
  size_25,
  size_540,
  size_75,
  size_160,
  size_100,
  size_2,
  size_6,
  size_13,
  txtSize_90,
  size_113,
  size_250,
} from 'constants/dimentions';
import {
  Default_Regular,
  HelveticaNeue_Bold,
  HelveticaNeue,
} from 'constants/fonts';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    paddingBottom: size_129,
    paddingLeft: size_90,
    paddingRight: size_110,
  },
  topWrapper: {
    flexDirection: 'row',
  },
  pieWrapper: {
    justifyContent: 'center',
    alignItems: 'center',
    width: size_500,
    height: size_500,
    borderRadius: size_250,
    marginTop: size_43,
    marginLeft: size_540,
    overflow: 'hidden',
  },
  innerWrapper: {
    padding: size_15,
    borderRadius: size_500,
    position: 'absolute',
    backgroundColor: PRIMARY_LIGHT,
  },
  piechartInner: {
    borderColor: PRIMARY_GRAY_BACKGROUND,
    borderWidth: borderRadius_10,
    width: size_405,
    height: size_405,
    borderRadius: size_214,
    justifyContent: 'center',
    alignItems: 'center',
  },
  piechartTitle: {
    fontSize: txtSize_36,
    fontFamily: HelveticaNeue_Bold,
    color: PRIMARY_DARK,
    lineHeight: size_52,
  },
  pieChartUnit: {
    textAlign: 'center',
    fontSize: txtSize_48,
    color: PRIMARY_BLUE,
    fontFamily: Default_Regular,
    lineHeight: size_60,
  },
  desciptionWrapper: {
    flex: 1,
    height: '100%',
    paddingTop: size_160,
    paddingLeft: size_100,
  },
  colorTagsWrapper: {position: 'absolute', top: size_75, left: 0},
  splitline: {
    backgroundColor: TABBAR_DISABLE_UNDERLINE,
    width: '100%',
    height: size_2,
    marginTop: size_10,
    marginBottom: size_15,
  },
  title: {
    color: PRIMARY_GRAY_BORDER,
    fontFamily: HelveticaNeue,
    fontSize: txtSize_22,
    lineHeight: size_32,
  },
  detailWrapper: {flexDirection: 'row', justifyContent: 'space-between'},
  detailName: {
    color: PRIMARY_DARK,
    fontFamily: HelveticaNeue_Bold,
    fontSize: txtSize_22,
    lineHeight: size_72,
    textAlignVertical: 'center',
    marginTop: size_13,
  },
  detailValue: {
    color: PRIMARY_LIGHT_BLUE,
    fontFamily: Default_Regular,
    lineHeight: size_72,
    fontSize: txtSize_48,
    letterSpacing: -1.2,
    width: '50%',
    textAlignVertical: 'center',
    marginTop: size_6,
  },
  detailUnit: {fontSize: txtSize_24},
  barchartWrapper: {
    width: '100%',
    flex: 1,
    marginTop: size_59,
    paddingLeft: size_25,
    overflow: 'visible',
  },
  barChart: {flex: 1, height: size_353},
  selfSuffiRateNumb: {
    lineHeight: size_113,
    letterSpacing: -2.25,
    fontFamily: Default_Regular,
    fontSize: txtSize_90,
    color: PRIMARY_BLUE,
  },
});
export default styles;
